;_____[ MessageBox-definitions ]__________________________________________________

;;;;;;;;;; button ;;;;;;;;;;
;;MBYES
;;MBNO
;;MBOK
;;MBCANCEL
;;MBCANCEL2
;;;;;;;;;; default button ;;;;;
;;MBDEF1
;;MBDEF2
;;MBDEF3
;;;;;;;;;; icon ;;;;;;;;;;
;;MBERR
;;MBQUES
;;MBWARN
;;MBINFO
;;;;;;;;;;

[Message]
NoDiskError=MBOK|MBWARN
LaunchError=MBOK|MBWARN
ColorError=MBOK|MBWARN
ResError=MBOK|MBWARN
OSError=MBOK|MBERR
DiskFullError=MBCANCEL2|MBWARN
MemoryError=MBOK|MBWARN
MutexError=MBOK|MBWARN
AssocError=MBOK|MBWARN
AssocErrorPDF=MBOK|MBWARN
AssocErrorHTML=MBOK|MBWARN
AssocErrorHTA=MBOK|MBWARN
AssocErrorTXT=MBOK|MBWARN
MsiMessage=MBOK|MBWARN
SysCloseMessage=MBYES|MBNO|MBWARN|MBDEF2
NoAdminError=MBOK|MBWARN
EjectError=MBOK|MBWARN|MBTOP

;_____[ SelectLang ]__________________________________________________
[Select Language-DlgCtrl OK]
LaunchFunc=DispatchSetLocale
LaunchData=TopMenu

[Select Language-DlgCtrl Cancel]
LaunchFunc=DispatchExit
MsgBoxFlag=MBYES|MBNO|MBWARN|MBDEF2

;_____[ TopMenu ]__________________________________________________
[TopMenu-Button Easy]
LaunchFunc=DispatchScreen
LaunchData=SelectItem

[TopMenu-Button Custom]
LaunchFunc=DispatchScreen
LaunchData=SelectItem

[TopMenu-Button Utility]
LaunchFunc=DispatchScreen
LaunchData=Utility

[TopMenu-Button Readme]
LaunchFunc=DispatchScreen
LaunchData=Manual

[TopMenu-Button Regist]
LaunchFunc=DispatchFileOpen

[TopMenu-Button Exit]
LaunchFunc=DispatchExit

;_____[ SelectPort ]__________________________________________________
;_____[ Manual ]__________________________________________________
[Manual-Button Back]
LaunchFunc=DispatchPreviousScreen

[Manual-Button Cancel]
LaunchFunc=DispatchExit
MsgBoxFlag=MBYES|MBNO|MBWARN|MBDEF2

[Manual-Item PrinterDriverInstallationGuide]
LaunchFunc=DispatchFileOpen

[Manual-Item e-Manual]
LaunchFunc=DispatchFileOpen


;_____[ Utility ]__________________________________________________
[Utility-Button Back]
LaunchFunc=DispatchPreviousScreen

[Utility-Button Cancel]
LaunchFunc=DispatchExit
MsgBoxFlag=MBYES|MBNO|MBWARN|MBDEF2

[Utility-Item NetworkTool]
LaunchFunc=DispatchProgram
LaunchParam=Lang=K Dev="Canon LBP6230/6240" handle=#h messageid=#m applicationid=#i

[Utility-Item ManualUninstaller]
LaunchFunc=DispatchProgram
LaunchParam=uninstall


;_____[ SelectItem ]__________________________________________________
[SelectItem-Button Install]
LaunchFunc=DispatchScreen
LaunchData=License

[SelectItem-Button Back]
LaunchFunc=DispatchScreen
LaunchData=TopMenu

[SelectItem-Button Cancel]
LaunchFunc=DispatchExit
MsgBoxFlag=MBYES|MBNO|MBWARN|MBDEF2

;_____[ License ]__________________________________________________
[License-Button Yes]
LaunchFunc=DispatchScreen
LaunchData=Installation

[License-Button No]
LaunchFunc=DispatchExit
MsgBoxFlag=MBYES|MBNO|MBWARN|MBDEF2

[License-Button Back]
LaunchFunc=DispatchPreviousScreen

;_____[ Installation ]__________________________________________________
[Installation-Button Next]
LaunchFunc=DispatchScreen
LaunchData=EndScreen
LaunchDataDrvInstSuc=eRegEndScreen

[Installation-Func NetworkSetting]
LaunchFunc=DispatchProgramSequential
LaunchParam=Lang=K Dev="Canon LBP6230/6240" handle=#h messageid=#m applicationid=#i
LaunchInterval=2000
WaitType=PROC_WNDMSG

[Installation-Func UFRIIPrinterDriver]
LaunchFunc=DispatchProgramSequential
LaunchParam=/W #h /P "DAGR=OFF DCMP=OFF DCMP_RBT=N"
LaunchInterval=2000
WaitType=BASE

[Installation-Func Manuals]
LaunchFunc=DispatchProgramSequential
LaunchParam=install handle=#h messageid=#m applicationid=#i timeout=#t
LaunchInterval=2000
WaitType=PROC_WNDMSG
WaitTime=120

[Installation-Func PESPPreInst]
LaunchFunc=DispatchProgramSequential
LaunchParam=-hw=#h -wmid=#m -lp=#i -MI
LaunchInterval=2000
WaitType=PROC_WNDMSG


;_____[ EndScreen ]__________________________________________________
[EndScreen-Button RebootCheck]
LaunchFunc=DispatchSwitch
LaunchData=RebootExit

[EndScreen-Button RebootExit]
LaunchFunc=DispatchRebootExit
MsgBoxFlagOnOff=MBYES|MBNO|MBWARN|MBDEF2

;_____[ eRegEndScreen ]__________________________________________________
[eRegEndScreen-Button Regist]
LaunchFunc=DispatchFileOpen

[eRegEndScreen-Button RebootCheck]
LaunchFunc=DispatchSwitch
LaunchData=RebootExit

[eRegEndScreen-Button RebootExit]
LaunchFunc=DispatchRebootExit
MsgBoxFlagOnOff=MBYES|MBNO|MBWARN|MBDEF2

