;_____[ Item Information ]__________________________________________________
[Item]
EasyItems=NetworkSetting|UFRIIPrinterDriver|Manuals|PESPPreInst
EasyItemsXPSP2=NetworkSetting|UFRIIPrinterDriver|Manuals
EasyItems2003=NetworkSetting|UFRIIPrinterDriver|Manuals
EasyItems2008=NetworkSetting|UFRIIPrinterDriver|Manuals
EasyItemsXP64=NetworkSetting|UFRIIPrinterDriver|Manuals
EasyItems200364=NetworkSetting|UFRIIPrinterDriver|Manuals
EasyItems200864=NetworkSetting|UFRIIPrinterDriver|Manuals
EasyItems201264=NetworkSetting|UFRIIPrinterDriver|Manuals

CustomItems=NetworkSetting|UFRIIPrinterDriver|Manuals|PESPPreInst
CustomItemsXPSP2=NetworkSetting|UFRIIPrinterDriver|Manuals
CustomItems2003=NetworkSetting|UFRIIPrinterDriver|Manuals
CustomItems2008=NetworkSetting|UFRIIPrinterDriver|Manuals
CustomItemsXP64=NetworkSetting|UFRIIPrinterDriver|Manuals
CustomItems200364=NetworkSetting|UFRIIPrinterDriver|Manuals
CustomItems200864=NetworkSetting|UFRIIPrinterDriver|Manuals
CustomItems201264=NetworkSetting|UFRIIPrinterDriver|Manuals

UtilityItems=NetworkTool|ManualUninstaller

ManualItems=PrinterDriverInstallationGuide|e-Manual


;;########################################
;;##
;;##  Driver / Application Installers
;;##
;;########################################

[Item NetworkSetting]
Hidden=1
WithDriver=1

[Item UFRIIPrinterDriver]
Icon=%r\..\image\Printerd.bmp
Transparency=253
DiskSpace=80
DiskSpacex64=110
DiskCheck=1
PrnDrv=1

[Item Manuals]
Icon=%r\..\image\Manual.bmp
Transparency=253
DiskCheck=1

[Item PESPPreInst]
MsiReq=1
PESP=1
Hidden=1


;;########################################
;;##
;;##  Start Software Programs
;;##
;;########################################

[Item NetworkTool]
Icon=%r\..\image\Network_Tool.bmp
Transparency=253
Button=H30GR

[Item ManualUninstaller]
Icon=%r\..\image\manual_un.bmp
Transparency=15
Button=H30GR


;;########################################
;;##
;;##  Manuals
;;##
;;########################################




