;_____[ Prototype-definitions ]__________________________________________________
[Prototype-Button topH54]
Font=Arial,20,0

[Prototype-Button topH48]
Font=Arial,18,0

[Prototype-Button topH37]
Font=Arial,17,0

[Prototype-Button topH37G]
Font=Arial,17,0

[Prototype-Button H37G]
Font=Arial,15,0

[Prototype-Button H37GR]
Font=Arial,15,0

[Prototype-Button H30GRL]
Font=Arial,15,0

[Prototype-Button H30GL]
Font=Arial,15,0

;_____[ SelectLang ]__________________________________________________
[Select Language-DlgCtrl Text1]
Font=Arial,15,0

[Select Language-DlgCtrl Title]
Font=Arial,15,0

[Select Language-DlgCtrl Text2]
Font=Arial,15,0

[Select Language-DlgCtrl ListBox]
Font=Arial,15,0

[Select Language-DlgCtrl OK]
Font=Arial,15,0

[Select Language-DlgCtrl Cancel]
Font=Arial,15,0

