;_____[ Config ]__________________________________________________
[Config]
RebootRestart=1
ConfSysClose=1
ScreenNames=TopMenu|SelectPort|SelectItem|Manual|Utility|License|Installation|EndScreen|eRegEndScreen
Startup=TopMenu
Bitmap=%r\..\image\background.bmp
ProtoButtons=topH54|topH48|topH37|topH37G|H37G|H37GR|H30GRL|H30GL
ItemButtons=H30GR

;_____[ Prototype-definitions ]__________________________________________________
[Prototype-Button topH54]
Shape=0,0|278,52|5,5
Normal=%r\..\image\topButtonH54_normal.bmp
High=%r\..\image\topButtonH54_over.bmp
Push=%r\..\image\topButtonH54_click.bmp
Disable=%r\..\image\topButtonH54_disable.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

[Prototype-Button topH48]
Shape=0,0|278,46|5,5
Normal=%r\..\image\topButtonH48_normal.bmp
High=%r\..\image\topButtonH48_over.bmp
Push=%r\..\image\topButtonH48_click.bmp
Disable=%r\..\image\topButtonH48_disable.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

[Prototype-Button topH37]
Shape=0,0|224,35|5,5
Normal=%r\..\image\topButtonH37_normal.bmp
High=%r\..\image\topButtonH37_over.bmp
Push=%r\..\image\topButtonH37_click.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

[Prototype-Button topH37G]
Shape=0,0|126,35|5,5
Normal=%r\..\image\topButtonH37g_normal.bmp
High=%r\..\image\topButtonH37g_over.bmp
Push=%r\..\image\topButtonH37g_click.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

[Prototype-Button H37G]
Shape=0,0|156,35|5,5
Normal=%r\..\image\ButtonH37g_normal.bmp
High=%r\..\image\ButtonH37g_over.bmp
Push=%r\..\image\ButtonH37g_click.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

[Prototype-Button H37GR]
Shape=0,0|156,35|5,5
Normal=%r\..\image\ButtonH37gr_normal.bmp
High=%r\..\image\ButtonH37gr_over.bmp
Push=%r\..\image\ButtonH37gr_click.bmp
Disable=%r\..\image\ButtonH37gr_disable.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

[Prototype-Button H30GRL]
Shape=0,0|153,28|5,5
Normal=%r\..\image\ButtonH30gr_L_normal.bmp
High=%r\..\image\ButtonH30gr_L_over.bmp
Push=%r\..\image\ButtonH30gr_L_click.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

[Prototype-Button H30GL]
Shape=0,0|153,28|5,5
Normal=%r\..\image\ButtonH30g_L_normal.bmp
High=%r\..\image\ButtonH30g_L_over.bmp
Push=%r\..\image\ButtonH30g_L_click.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

;_____[ Item-Button-definitions ]__________________________________________________
[Item-Button H30GR]
Shape=0,0|131,28|5,5
Normal=%r\..\image\ButtonH30gr_normal.bmp
High=%r\..\image\ButtonH30gr_over.bmp
Push=%r\..\image\ButtonH30gr_click.bmp
Color=0
ColorH=255
ColorG=160
ColorP=255
ColorS=255
ColorHS=0
ColorGS=255
ColorPS=0
OffsetShadow=1
OffsetPush=2
OffsetTabRect=2

;_____[ SelectLang ]__________________________________________________
[Dialog Select Language]
Width=474
Height=347

[Select Language-DlgCtrl Text1]
Position=11,11
Width=452
Height=37

[Select Language-DlgCtrl Title]
Position=11,48
Width=452
Height=20

[Select Language-DlgCtrl Text2]
Position=11,242
Width=452
Height=71

[Select Language-DlgCtrl ListBox]
Position=11,68
Width=452
Height=163

[Select Language-DlgCtrl OK]
Position=284,313
Width=86
Height=23

[Select Language-DlgCtrl Cancel]
Position=377,313
Width=86
Height=23


;_____[ TopMenu ]__________________________________________________
[Screen TopMenu]
ResetItem=1
ConfSysClose=0
BitmapNames=LSide
ButtonNames=Easy|Custom|Utility|Readme|Regist|Exit
LabelNames=Title|EasyInfo|CustomInfo|UtilityInfo|ReadmeInfo|RegistInfo

[TopMenu-Label Title]
Title=1
Position=260,24
Color=0

[TopMenu-Bitmap LSide]
Bitmap=%r\..\image\topimage.bmp
Position=0,0

;;;;;;;; button position ;;;;;;;;
;;
;;;; With Easy button
;;
;; 3 buttons
;; Position=486,63
;; Position=260,121
;; Position=486,157
;; Position=260,209
;; Position=638,509
;;
;; 3 buttons
;; Position=486,63
;; Position=260,121
;; Position=540,168
;; Position=260,209
;; Position=638,509
;;
;; 4 buttons
;; Position=486,63
;; Position=260,121
;; Position=486,157
;; Position=260,209
;; Position=486,245
;; Position=260,297
;; Position=638,509
;;
;; 5 buttons
;; Position=486,63
;; Position=260,121
;; Position=486,157
;; Position=260,209
;; Position=486,245
;; Position=260,297
;; Position=540,344
;; Position=260,385
;; Position=638,509
;;
;; 6 buttons
;; Position=486,63
;; Position=260,121
;; Position=486,157
;; Position=260,209
;; Position=486,245
;; Position=260,297
;; Position=540,344
;; Position=260,385
;; Position=540,421
;; Position=260,462
;; Position=638,509
;;
;;;; Without Easy button
;;
;; 2 buttons
;; Position=486,63
;; Position=260,121
;; Position=638,509
;;
;; 3 buttons
;; Position=486,63
;; Position=260,121
;; Position=540,168
;; Position=260,209
;; Position=638,509
;;
;; 4 buttons
;; Position=486,63
;; Position=260,121
;; Position=540,168
;; Position=260,209
;; Position=540,245
;; Position=260,286
;; Position=638,509
;;
;; 5 buttons
;; Position=486,63
;; Position=260,121
;; Position=486,157
;; Position=260,209
;; Position=540,256
;; Position=260,297
;; Position=540,333
;; Position=260,374
;; Position=638,509
;;
;;;;;;;;

[TopMenu-Button Easy]
TabOrder=0
Position=486,63
Custom=0
AdminReq=1
Prototype=topH54

[TopMenu-Label EasyInfo]
Position=260,121
TextAlign=Right|29
Color=0

[TopMenu-Button Custom]
TabOrder=1
Position=486,157
Custom=1
AdminReq=1
Prototype=topH48

[TopMenu-Label CustomInfo]
Position=260,209
TextAlign=Right|29
Color=0

[TopMenu-Button Utility]
TabOrder=2
Position=486,245
Prototype=topH48

[TopMenu-Label UtilityInfo]
Position=260,297
TextAlign=Right|29
Color=0

[TopMenu-Button Readme]
TabOrder=3
Position=540,344
Prototype=topH37

[TopMenu-Label ReadmeInfo]
Position=260,385
TextAlign=Right|29
Color=0

[TopMenu-Button Regist]
TabOrder=4
Position=540,421
Prototype=topH37

[TopMenu-Label RegistInfo]
Position=260,462
TextAlign=Right|29
Color=0

[TopMenu-Button Exit]
TabOrder=5
Position=638,509
Prototype=topH37G


;_____[ SelectPort ]__________________________________________________

;_____[ Manual ]__________________________________________________
[Screen Manual]
ItemType=MANUAL
ButtonNames=Back|Cancel
LabelNames=Title|Text1

[Manual-Label Title]
Title=1
Position=18,18
Color=0,51,153

[Manual-Label Text1]
Position=18,55
Color=0

[Manual-Button Back]
Prototype=H37G
TabOrder=1
Position=18,515

[Manual-Button Cancel]
Prototype=H37G
TabOrder=2
Position=614,515

[Manual-Item-Common]
TabOrder=0
;; Position=window-width,window-y-coordinate
Position=18,110
WndHeight=365
WidthR=0
Color=0
ColorTab=0
ColorItemName=0,51,153
ColorLink=0,102,204
ColorLinkH=51,153,255
IconHTML=%r\..\image\manual_html.bmp

;_____[ Utility ]__________________________________________________
[Screen Utility]
ItemType=UTILITY
ButtonNames=Back|Cancel
LabelNames=Title|Text1

[Utility-Label Title]
Title=1
Position=18,18
Color=0,51,153

[Utility-Label Text1]
Position=18,55
Color=0

[Utility-Button Back]
Prototype=H37G
TabOrder=1
Position=18,518

[Utility-Button Cancel]
Prototype=H37G
TabOrder=2
Position=614,518

[Utility-Item-Common]
TabOrder=0
;; Position=window-width,window-y-coordinate
Position=18,110
WndHeight=365
WidthR=133
Color=0
ColorTab=0
ColorItemName=0,51,153
ColorLink=0,102,204
ColorLinkH=51,153,255

;_____[ SelectItem ]__________________________________________________
[Screen SelectItem]
ItemType=SELECT
ButtonNames=Install|Back|Cancel
LabelNames=Title|Text1|FreeVol|InstVol|FreeVolText|InstVolText
UnitByte=M

[SelectItem-Label Title]
Title=1
Position=18,18
Color=0,51,153

[SelectItem-Label Text1]
Position=18,55
Color=0

[SelectItem-Label FreeVol]
Position=372,485
TextAlign=RIGHT|318

[SelectItem-Label InstVol]
Position=672,485
TextAlign=RIGHT|18

[SelectItem-Label FreeVolText]
Position=172,485
TextAlign=RIGHT|418

[SelectItem-Label InstVolText]
Position=472,485
TextAlign=RIGHT|118

[SelectItem-Button Install]
Prototype=H37GR
TabOrder=0
Position=445,518
DiskCheck=1

[SelectItem-Button Back]
Prototype=H37G
TabOrder=2
Position=18,518

[SelectItem-Button Cancel]
Prototype=H37G
TabOrder=3
Position=614,518

[SelectItem-Item-Common]
TabOrder=1
;; Position=window-width,window-y-coordinate
Position=18,110
WndHeight=365
WidthR=70
Color=0
ColorTab=0
ColorItemName=0,51,153
ColorLink=0,102,204
ColorLinkH=51,153,255

;_____[ License ]__________________________________________________
[Screen License]
ButtonNames=Yes|No|Back
LicenseNames=License
LabelNames=Title|Text1|Text2
Progress=License

[License-Label Title]
Title=1
Position=18,18
Color=0,51,153

[License-Label Text1]
Position=18,55
Color=0

[License-Label Text2]
Position=18,452
Color=0

[License-Button Yes]
Prototype=H37GR
TabOrder=1
Position=445,518

[License-Button No]
Prototype=H37G
TabOrder=2
Position=614,518

[License-Button Back]
Prototype=H37G
TabOrder=3
Position=18,518

[License-License-Common]
Color=0

[License-License License]
TabOrder=0
Position=18,110
Width=754
Height=331
License=%r\License.txt

;_____[ Installation ]__________________________________________________
[Screen Installation]
SysClose=0
ConfSysClose=0
ItemType=PROGRESS
ButtonNames=Next
LabelNames=Title|Text1

[Installation-Label Title]
Title=1
Position=18,18
Color=0,51,153
[Installation-Label Text1]
Position=18,55
Color=0

[Installation-Button Next]
Prototype=H37GR
TabOrder=0
Position=614,518

[Installation-Item-Common]
TabOrder=1
Position=18,110
WndHeight=365
Width=754
WidthR=0
Color=0,0,0
ColorItemName=0,51,153
CheckOn=%r\..\image\ok.bmp
CheckOff=%r\..\image\ng.bmp

;_____[ EndScreen ]__________________________________________________
[Screen EndScreen]
SysClose=0
ButtonNames=RebootExit|RebootCheck
LabelNames=Title
LinkNames=RebootCheck

[EndScreen-Label Title]
Title=1
Position=18,18
Color=0,51,153

[EndScreen-Button RebootCheck]
TabOrder=1
Type=CHECK
Position=18,55
ColorTab=85
AttachID=Reboot

[EndScreen-Link RebootCheck]
Position=38,55
ColorN=0
AttachButton=Reboot

[EndScreen-Button RebootExit]
Prototype=H37GR
TabOrder=0
Type=BUTTON
Position=614,518

;_____[ eRegEndScreen ]__________________________________________________
[Screen eRegEndScreen]
SysClose=0
ButtonNames=Regist|RebootExit|RebootCheck
LabelNames=Title|Text1
LinkNames=RebootCheck

[eRegEndScreen-Label Title]
Title=1
Position=18,18
Color=0,51,153

[eRegEndScreen-Label Text1]
Position=18,55

[eRegEndScreen-Button Regist]
Prototype=topH37
TabOrder=0
Position=546,110

[eRegEndScreen-Button RebootCheck]
TabOrder=2
Type=CHECK
Position=18,480
ColorTab=85
AttachID=Reboot

[eRegEndScreen-Link RebootCheck]
Position=38,480
ColorN=0
AttachButton=Reboot

[eRegEndScreen-Button RebootExit]
Prototype=H37GR
TabOrder=1
Type=BUTTON
Position=614,518

