function fncSearchKeyDown(a,e){try{if(13==a)return document.getElementById("id_search_button").click(),!1;e==fncGetResourceByResourceId("enter_search_keyword")&&document.getElementById("id_search")&&(document.getElementById("id_search").value="",document.getElementById("id_search").style.color="#000000");return!0}catch(d){}}
function fncOpenSubWindow(a,e){try{if("_blank"==e)var d=window.open(a,e);else if("theme"==e)var f=1024,b=768,g=screen.width/2-f/2,h=screen.height/2-b/2,d=window.open(a+"?theme=yes",e,"directories=no,location=no,menubar=no,status=no,toolbar=no,resizable=yes,width="+f+",top="+h+",left="+g+",height="+b+",scrollbars=yes");else f=640,b=480,g=screen.width/2-f/2,h=screen.height/2-b/2,d=window.open(a+"?sub=yes",e,"directories=no,location=no,menubar=no,status=no,toolbar=no,resizable=yes,width="+f+",top="+
h+",left="+g+",height="+b);d.focus()}catch(p){}}function fncPrint(){try{window.print()}catch(a){}}function fncKeyPress(){try{27==event.keyCode&&window.close()}catch(a){}}
function fncGetTocHrefAndTitleByLinkName(a){try{for(var e=eval(toc),d=e.length,f=0;f<d;f++){var b;if(e[f].link_name){if(b=e[f].link_name,""==b)continue}else if(e[f].type){if(b=e[f].type,""==b)continue}else continue;var g=b.indexOf("::");-1!=g&&(b=b.substring(g+2));if(b==a)return"../contents/"+e[f].href+"___DELIMITER___"+e[f].title}return!1}catch(h){}}
function fncGetTocIdByLinkName(a){try{var e=eval(toc);if(!a)return e[0].id;for(var d=e.length,f=0;f<d;f++){var b;if(e[f].link_name){if(b=e[f].link_name,""==b)continue}else if(e[f].type){if(b=e[f].type,""==b)continue}else continue;var g=b.indexOf("::");-1!=g&&(b=b.substring(g+2));if(b==a)return e[f].id}return!1}catch(h){}}function fncGetTocById(a){try{for(var e=eval(toc),d=e.length,f=0;f<d;f++)if(e[f].id==a)return e[f];return!1}catch(b){}}
function fncGetTocNodeByLinkName(a){try{for(var e=eval(toc),d=e.length,f=0;f<d;f++){var b;if(e[f].link_name&&(b=e[f].link_name,""!=b)){var g=b.indexOf("::");-1!=g&&(b=b.substring(g+2));if(b==a)return e[f]}}return!1}catch(h){}}
function fncGetSiblingNodeId(a){try{for(var e=eval(toc),d=e.length,f=":",b=0;b<d;b++){if(0==b&&""==a)return f+e[b].id;if(e[b].id==a){if(0==b)f="../frame_htmls/home"+f;else for(var g=b;0<g;){if(e[g-1]&&"n"!=e[g-1].show_toc){f=e[g-1].id+f;break}g--}for(g=b;g<=d;){if(e[g+1]&&"n"!=e[g+1].show_toc){f+=e[g+1].id;break}g++}break}}return f}catch(h){}}function fncGetResourceByResourceId(a){try{for(var e=eval(resource),d=e.length,f=0;f<d;f++)if(e[f].id==a)return e[f].value;return""}catch(b){}}
function fncIncludeHeader(){try{if(header){for(var a=[],e=header.split(","),d=e.length,f=0;f<d;f++)switch(e[f]){case "config":a.push('<button id="config"></button>');break;case "help":a.push('<button id="help"></button>');break;case "|":a.push('<img class="header_vr" src="'+frame_path+'images/hdr_vr.gif" />');break;case "_SEARCH_":break;default:a.push('<a id="id_link_'+e[f]+'"></a>')}document.getElementById("id_header_include").innerHTML=a.join("")}}catch(b){}}
function fncIncludeFooter(){try{if(footer){for(var a=[],e=footer.split(","),d=e.length,f=0;f<d;f++)switch(e[f]){case "|":a.push('<img class="footer_vr" src="'+frame_path+'images/ftr_vr.gif" />');break;case "_PUBNO_":a.push('<span id="id_res_pub_number"></span>');break;default:a.push('<a id="id_link_'+e[f]+'"></a>')}document.getElementById("id_footer_include").innerHTML=a.join("")}}catch(b){}}
function fncLoadResource(){try{for(var a=eval(resource),e=a.length,d="",f=0;f<e;f++){if(document.getElementById("id_res_"+a[f].id)){var b=a[f].value;frame_path&&(b=b.replace(/___frame_path___/,frame_path));document.getElementById("id_res_"+a[f].id).innerHTML=b}if(("product_main_name"==a[f].id||"product_sub_name"==a[f].id||"version"==a[f].id||"guide_name"==a[f].id)&&""!=a[f].value)"guide_name"==a[f].id&&(d+=" - "),d+=a[f].value.replace(/<br>|<br\/>|<br \/>/gi,"").replace(/&#x200b;/gi,"")+" "}""==document.title?
document.title="Canon - "+d:"HOME_TOC"!=strWindowType&&(document.title+=" - Canon - "+d);document.title=document.title.replace(/&shy;|/gi,"").replace(/&#x200b;/gi,"")}catch(g){}}
function fncGenerateDynamicLink(a){try{for(var e=eval(link_info),d=e.length,f=0;f<d;f++){var b=e[f].link_name,g=e[f].link_target,h=e[f].link_resource;h||(h=b);void 0!=a&&(g=a);for(var p=$("*[id=id_link_"+b+"]"),k=p.length,r=0;r<k;r++){var m=p[r];if(m){var v=fncGetTocHrefAndTitleByLinkName(b),s=null,u=null;v&&(s=v.split("___DELIMITER___")[0],u=v.split("___DELIMITER___")[1]);s||(s=e[f].link_href);m.link_href=s;var t=m.nodeName.toLowerCase();if("a"==t){var q=fncGetResourceByResourceId(h);q||(q=u);q&&
(m.innerHTML=q,m.title=q.replace(/&quot;/g,'"').replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&"));if("_self"==g){m.href=s;if(-1!=s.indexOf(".pdf")){if(ga_tracking_id)try{ga("send","event",s,"click","pdf downloads",4)}catch(C){}if("local"!=asset_mode&&multitrack_id&&ga2)try{ga2("send","event",s,"click","pdf downloads",4)}catch(D){}}m.className="self"}else m.href="#",m.link_target=g,"canon_sub_window"==g&&(m.className="sub_window"),m.onclick=function(){if(-1!=this.link_href.indexOf(".pdf")){if(ga_tracking_id)try{ga("send",
"event",this.link_href,"click","pdf downloads",4)}catch(a){}if("local"!=asset_mode&&multitrack_id&&ga2)try{ga2("send","event",this.link_href,"click","pdf downloads",4)}catch(b){}}fncOpenSubWindow(this.link_href,this.link_target)}}else"li"==t?((q=fncGetResourceByResourceId(h))||(q=u),q&&(m.innerHTML=q,m.title=q.replace(/&quot;/g,'"').replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&")),m.style.cursor="pointer",m.onclick=function(){document.location.href=this.link_href;if(-1!=this.link_href.indexOf(".pdf")){if(ga_tracking_id)try{ga("send",
"event",this.link_href,"click","pdf downloads",4)}catch(a){}if("local"!=asset_mode&&multitrack_id&&ga2)try{ga2("send","event",this.link_href,"click","pdf downloads",4)}catch(b){}}}):"button"==t?((q=fncGetResourceByResourceId(h))||(q=u),q&&(m.title=q.replace(/&quot;/g,'"').replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&")),"_self"==g?m.onclick=function(){document.location.href=this.link_href}:(m.link_target=g,m.onclick=function(){fncOpenSubWindow(this.link_href,this.link_target);if(-1!=
this.link_href.indexOf(".pdf")){if(ga_tracking_id)try{ga("send","event",this.link_href,"click","pdf downloads",4)}catch(a){}if("local"!=asset_mode&&multitrack_id&&ga2)try{ga2("send","event",this.link_href,"click","pdf downloads",4)}catch(b){}}}),m.childNodes[0]||(m.innerHTML='<img src="'+frame_path+"images/"+b+'_out.png" />',m.link_name=b,m.onmouseover=function(){this.childNodes[0].src=""+frame_path+"images/"+this.link_name+"_over.png"},m.onmouseout=function(){this.childNodes[0].src=""+frame_path+
"images/"+this.link_name+"_out.png"})):"img"==t&&((q=fncGetResourceByResourceId(h))||(q=u),q&&(m.title=q.replace(/&quot;/g,'"').replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&")),m.style.cursor="Pointer","_self"==g?m.onclick=function(){if(-1!=this.link_href.indexOf(".pdf")){if(ga_tracking_id)try{ga("send","event",this.link_href,"click","pdf downloads",4)}catch(a){}if("local"!=asset_mode&&multitrack_id&&ga2)try{ga2("send","event",this.link_href,"click","pdf downloads",4)}catch(b){}}document.location.href=
this.link_href}:(m.link_target=g,m.onclick=function(){if(-1!=this.link_href.indexOf(".pdf")){if(ga_tracking_id)try{ga("send","event",this.link_href,"click","pdf downloads",4)}catch(a){}if("local"!=asset_mode&&multitrack_id&&ga2)try{ga2("send","event",this.link_href,"click","pdf downloads",4)}catch(b){}}fncOpenSubWindow(this.link_href,this.link_target)}))}}var n=document.getElementById("id_button_"+b);n&&(v=fncGetTocHrefAndTitleByLinkName(b),u=s=null,v&&(s=v.split("___DELIMITER___")[0],u=v.split("___DELIMITER___")[1]),
s||(s=e[f].link_href),n.link_href=s,t=n.nodeName.toLowerCase(),"button"==t?((q=fncGetResourceByResourceId(h))||(q=u),q&&(n.title=q),"_self"==g?n.onclick=function(){document.location.href=this.link_href}:(n.link_target=g,n.onclick=function(){fncOpenSubWindow(this.link_href,this.link_target)}),n.childNodes[0]||(n.innerHTML='<img src="'+frame_path+"images/"+b+'_out.png" />',n.link_name=b,n.onmouseover=function(){this.childNodes[0].src=frame_path+"images/"+this.link_name+"_over.png"},n.onmouseout=function(){this.childNodes[0].src=
frame_path+"images/"+this.link_name+"_out.png"})):"img"==t&&((q=fncGetResourceByResourceId(h))||(q=u),q&&(n.title=q),n.src="../images/"+b+"_out.png",n.link_name=b,n.onmouseover=function(){this.src="../images/"+this.link_name+"_over.png"},n.onmouseout=function(){this.src="../images/"+this.link_name+"_out.png"},n.style.cursor="Pointer","_self"==g?n.onclick=function(){document.location.href=this.link_href}:(n.link_target=g,n.onclick=function(){fncOpenSubWindow(this.link_href,this.link_target)})))}}catch(A){}}
function fncResizeFrame(){try{var a=fncGetWindowWidth(),e=fncGetWindowHeight();document.getElementById("id_body")&&(document.getElementById("id_body").style.height=e-70+"px",document.getElementById("id_body").style.width=a+"px");document.getElementById("id_footer")&&(document.getElementById("id_footer").style.top=e-26+"px",document.getElementById("id_footer").style.width=a+"px")}catch(d){}}
function fncSearchBox(){try{$.browser.msie&&9>=parseInt($.browser.version)&&document.getElementById("id_search")&&(""==document.getElementById("id_search").value&&(document.getElementById("id_search").value=fncGetResourceByResourceId("enter_search_keyword"),document.getElementById("id_search").style.color="#808080"),document.getElementById("id_search").value==fncGetResourceByResourceId("enter_search_keyword")&&(document.getElementById("id_search").style.color="#808080"),document.getElementById("id_search").onclick=
function(){this.value==fncGetResourceByResourceId("enter_search_keyword")&&(this.value="",document.getElementById("id_search").style.color="#000000")},document.getElementById("id_search").onblur=function(){""==this.value&&(this.value=fncGetResourceByResourceId("enter_search_keyword"),document.getElementById("id_search").style.color="#808080")})}catch(a){}}
function fncDoSearch(a){try{var e=document.getElementsByTagName("html")[0].attributes["xml:lang"].value,d=document.getElementById("id_search").value,f=d=d.trim();if(""==d||d==fncGetResourceByResourceId("enter_search_keyword"))return document.getElementById("id_search_results")&&-1!=document.getElementById("id_search_results").innerHTML.indexOf(fncGetResourceByResourceId("search_message_wait"))&&fncResetSearchDisplay(),!1;fncSetSessionStorage("SEARCH-KEYWORD",d);var b=/([$()\-^\\\|\[\]{},:+*.?])/g;
null!=b.exec(d)&&(d=d.replace(b,"\\$1"));b=/(&)/g;null!=b.exec(d)&&(d=d.replace(b,"&amp;"),f=f.replace(b,"&amp;"));b=/(<)/g;null!=b.exec(d)&&(d=d.replace(b,"&lt;"),f=f.replace(b,"&lt;"));b=/(>)/g;null!=b.exec(d)&&(d=d.replace(b,"&gt;"),f=f.replace(b,"&gt;"));for(var g=!1,h=[],p=d.length,b=0;b<p;b++){var k=d.substring(b,b+1);if('"'==k||"\u201d"==k||"\u201c"==k)k="",g=!g;else if(g&&(" "==k||"\u3000"==k||"\t"==k||"\u00a0"==k))k="___SPACE___";h.push(k)}d=h.join("");g=!1;h=[];p=f.length;for(b=0;b<p;b++){k=
f.substring(b,b+1);if('"'==k||"\u201d"==k||"\u201c"==k)k="",g=!g;else if(g&&(" "==k||"\u3000"==k||"\t"==k||"\u00a0"==k))k="___SPACE___";h.push(k)}for(var f=h.join(""),k=/[\s\u3000]+/,r=d.split(k),m=f.split(k),p=r.length,b=0;b<p;b++)""==r[b]&&r.splice(b,1);p=m.length;for(b=0;b<p;b++)""==m[b]&&m.splice(b,1);if(""==r.join(""))return document.getElementById("id_search").value=fncGetResourceByResourceId("enter_search_keyword"),document.getElementById("id_search").style.color="#808080",document.getElementById("id_search_results")&&
-1!=document.getElementById("id_search_results").innerHTML.indexOf(fncGetResourceByResourceId("search_message_wait"))&&fncResetSearchDisplay(),!1;p=r.length;for(b=0;b<p;b++)r[b]=r[b].replace(/___SPACE___/g," ");p=m.length;for(b=0;b<p;b++)m[b]=m[b].replace(/___SPACE___/g," ");if(document.getElementById("id_search_chapters")){for(var v=document.getElementById("id_search_chapters").getElementsByTagName("input"),p=v.length,d=[],k=[],b=0;b<p;b++)v[b].checked?d.push(v[b].id):k.push(v[b].id);if(d.length!=
p&&(0==d.length||document.getElementById("id_search_options_search_scope_all").checked))d=k}var s=fncGetConstantByName("search_show_around");s||(s=50);var d=v=s,u=fncGetConstantByName("search_show_result_count");u||(u=10);var t=fncGetConstantByName("search_page_max_range");t||(t=5);parseInt(t/2);parseInt(t/2);t=0;k=[];if("GLOSSARY"!=strWindowType)for(var q=0,p=m.length,b=0;b<p;b++)q++,10<=q&&(q=0);for(var C=eval(search),D=r.length,g=0;g<D;g++){var n=r[g];1==fncGetConstantByName("search_option_multibyte")&&
(n=fncConvertSearchText(n,!0),r[g]=n);var A="i";document.getElementById("id_search_options_case")?document.getElementById("id_search_options_case").checked&&(A=""):"GLOSSARY"==strWindowType?A="":"TRUE"==fncGetSessionStorage("SEARCH-OPTIONS-CASE")&&(A="")}h="";document.location.search&&-1!=document.location.search.indexOf("?search=")&&(h=document.location.search.split("?search=")[1],h=h.split("&word=yes")[0],h=-1!=h.indexOf("&marking=no")?"":h.split("&marking=")[0],""!=h&&(h=decodeURIComponent(h),
h=h.trim(),h==fncGetResourceByResourceId("enter_search_keyword")&&(h="")));p=C.length;for(b=0;b<p;b++){var z=C[b].body,G=C[b].toc_id,H=C[b].title;if(z)for(var D=r.length,K=[],g=0;g<D;g++){var n=r[g],E="("+n+")";"GLOSSARY"==strWindowType&&(null==e.match(/ja|zh|ko/)&&null==n.match(/([()])/))&&(E="\\b("+n+")\\b");var L=RegExp(E,A);if(null==L.exec(z))break;else if(m[g].length>s)K.push(m[g]);else{var F=z.search(L);if(-1!=F){var B="",M=z.substring(0,F),N=M.lastIndexOf("&");"&"!=n&&-1!=N&&(B=M.substring(N));
var O="";if(-1==m[g].indexOf(";")){var P=z.substring(F+m[g].length),Q=P.indexOf(";");";"!=m[g]&&-1!=Q&&(O=P.substring(0,Q+1))}var I=B+m[g].toLowerCase()+O;if("&amp;"==I||"&lt;"==I||"&gt;"==I||"&quot;"==I)break;for(var J=z.substring(F-v-0,F+d+m[g].length+0);;)if(null!=J.substring(0,1).match(/[\u0E31]|[\u0E47-\u0E4E]|[\u0E34-\u0E3A]/))J=J.substring(1);else break;K.push(J)}}if(g==r.length-1&&(t++,a*u>=t+0&&a*u-u<t+0)){for(var l=K.join(String.fromCharCode(8230)),B=q=0;B<D;B++){switch(q){case 0:strMarkerColor=
String.fromCharCode(8320);break;case 1:strMarkerColor=String.fromCharCode(8321);break;case 2:strMarkerColor=String.fromCharCode(8322);break;case 3:strMarkerColor=String.fromCharCode(8323);break;case 4:strMarkerColor=String.fromCharCode(8324);break;case 5:strMarkerColor=String.fromCharCode(8325);break;case 6:strMarkerColor=String.fromCharCode(8326);break;case 7:strMarkerColor=String.fromCharCode(8327);break;case 8:strMarkerColor=String.fromCharCode(8328);break;case 9:strMarkerColor=String.fromCharCode(8329)}n=
r[B];n=n.replace(/&amp;/g,String.fromCharCode(726));n=n.replace(/&quot;/g,String.fromCharCode(698));n=n.replace(/&lt;/g,String.fromCharCode(753));n=n.replace(/&gt;/g,String.fromCharCode(754));E="("+n+")";"GLOSSARY"==strWindowType&&(E="\\b("+n+")\\b");var S=RegExp(E,"g"+A),l=l.replace(/&amp;/g,String.fromCharCode(726)),l=l.replace(/&quot;/g,String.fromCharCode(698)),l=l.replace(/&lt;/g,String.fromCharCode(753)),l=l.replace(/&gt;/g,String.fromCharCode(754)),l=l.replace(S,function(a,b,d){return String.fromCharCode(8261)+
strMarkerColor+a+String.fromCharCode(8262)}),l=l.replace(/\u02D6/g,"&amp;"),l=l.replace(/\u02BA/g,"&quot;"),l=l.replace(/\u02F1/g,"&lt;"),l=l.replace(/\u02F2/g,"&gt;");q++;10<=q&&(q=0)}var T=RegExp("\u2046","g"),l=l.replace(RegExp("\u2045([\u2080-\u2089])","g"),'<span class="hit hit_$1">'),l=l.replace(T,"</span>"),l=l.replace(/\u2080/g,"0"),l=l.replace(/\u2081/g,"1"),l=l.replace(/\u2082/g,"2"),l=l.replace(/\u2083/g,"3"),l=l.replace(/\u2084/g,"4"),l=l.replace(/\u2085/g,"5"),l=l.replace(/\u2086/g,"6"),
l=l.replace(/\u2087/g,"7"),l=l.replace(/\u2088/g,"8"),l=l.replace(/\u2089/g,"9"),l=l.replace(/\u2026/g,"..."),l=l.replace(/\u00b6+/g,'<span style="color:#C0C0C0"><img src="'+frame_path+'images/src_para.gif" /></span>');k.push('<div class="search_topic_title">');k.push("&nbsp;");G==document.body.toc_id?h==document.getElementById("id_search").value?k.push('<a class="current" href="javascript:fncOpenTopic(\''+G+"', "+a+');void(0);" title="'+H+'">'):k.push("<a href=\"javascript:fncOpenTopic('"+G+"', "+
a+');void(0);" title="'+H+'">'):k.push("<a href=\"javascript:fncOpenTopic('"+G+"', "+a+');void(0);" title="'+H+'">');k.push(H);k.push("</a>");k.push("</div>");k.push('<div class="search_topic_summary">');k.push("...");k.push(l);k.push("...");k.push("</div>")}}}var x=document.getElementById("id_search_texts");x?x.value=f:(x=document.createElement("input"),x.id="id_search_texts",x.type="hidden",x.value=f,document.getElementById("id_panel_search").appendChild(x));var y=document.getElementById("page");
y?y.value=a:(y=document.createElement("input"),y.id="page",y.type="hidden",y.value=a,document.getElementById("id_panel_search").appendChild(y));document.getElementById("id_search_results").innerHTML+=k.join("");document.getElementById("id_search_results").style.backgroundColor="#fff";"pc"==fncGetLayoutMode()&&(device.tablet()||document.getElementById("id_search").select());var R=parseInt(t/u);0!=t%u&&R++;e=[];e.push(fncGetResourceByResourceId("search_result_item"));e.push(' <span style="color: #cf4e32;">'+
t+"</span> "+fncGetResourceByResourceId("search_found"));document.getElementById("id_search_info").innerHTML=e.join("");var w=document.getElementById("more");w&&w.parentNode.parentNode.removeChild(w.parentNode);a+1<=R&&(more_div=document.createElement("div"),more_div.className="more",w=document.createElement("button"),w.id="more",w.innerHTML=fncGetResourceByResourceId("search_message_more"),w.onclick=function(){fncDoSearch(parseInt(document.getElementById("page").value)+1)},document.getElementById("id_search_results").appendChild(more_div),
more_div.appendChild(w))}catch(U){}}function fncClearSearch(){document.getElementById("id_search_results")&&(document.getElementById("id_search_results").scrollTop=0,document.getElementById("id_search_results").innerHTML="")}function fncSearchResultScroll(a){document.getElementById("id_search_results").scrollTop=a}
function fncOpenTopic(a,e){try{var d=encodeURIComponent(document.getElementById("id_search").value),f=fncGetResourceByResourceId("webfaq_link_html_file_name"),b=fncGetResourceByResourceId("webfaq_url"),g="_self";if(f&&b&&-1!=(a+".html").indexOf(f)&&"local"!=asset_mode)var h="/"+b+"&manual_url="+location.pathname.split("/")[1],g="CANON_WEB_FAQ";else h="../contents/"+a+".html?search="+d;fncSetSearchResultsInfo(e);"GLOSSARY"==strWindowType&&(h+="&word=yes");"HOME"==strWindowType&&(h+="&marking=no");
window.open(h,g)}catch(p){window.open(h)}}function fncSetSearchResultsInfo(a){try{document.getElementById("id_search_results")&&"GLOSSARY"!=strWindowType&&fncSetSessionStorage("SEARCH-RESULT-SETTING",a+":"+document.getElementById("id_search_results").scrollTop+":"+$("#page").val())}catch(e){}}function fncGetChapterTitle(a){try{for(var e=c.length,d=0;d<e;d++)if(c[d].id==a)return c[d].title}catch(f){}}
function fncToggleSearchOptions(){try{document.getElementById("id_search_options")&&("none"!=document.getElementById("id_search_options").style.display.toLowerCase()?(document.getElementById("id_search_options").style.display="None",document.getElementById("id_search_options_label").innerHTML='<a href="#" onclick="fncToggleSearchOptions();" title="'+fncGetResourceByResourceId("search_options_show")+'"><img src="'+frame_path+'images/srch_opt_show.gif" title="[+]" />'+fncGetResourceByResourceId("search_options_show")+
"</a>"):(document.getElementById("id_search_options").style.display="Block",document.getElementById("id_search_options_label").innerHTML='<a href="#" onclick="fncToggleSearchOptions();" title="'+fncGetResourceByResourceId("search_options_hide")+'"><img src="'+frame_path+'images/srch_opt_hide.gif" title="[-]" />'+fncGetResourceByResourceId("search_options_hide")+"</a>"),fncOnResize())}catch(a){}}
function fncGenerateChapterCheckbox(a,e){return'<div><input class="input_chapter" type="checkbox" id="id_'+a+'" onclick="fncSelectChaptersFromBelow();" /><label for="id_'+a+'" title="'+e+'">'+e+"</label></div>"}function fncSelectChaptersFromBelow(){try{document.getElementById("id_search_options_search_scope_chapter").checked=!0}catch(a){}}
function fncSelectChaptersFromAll(){try{for(var a=document.getElementById("id_search_chapters").getElementsByTagName("input"),e=a.length,d=0;d<e;d++)a[d].checked=!1}catch(f){}}function fncGetConstantByName(a){try{return eval(constant)[0][a]}catch(e){}}function fncGetWindowWidth(){try{var a=$(window).width();$(window).height();return a}catch(e){}}
function fncGetWindowHeight(){try{var a=window;if(window.opera)var e=a.innerHeight;else document.all?e=a.document.body.clientHeight:document.getElementById&&(e=a.innerHeight);return e}catch(d){}}function fncGetCookiePrefixName(){try{return"CANON-EMANUAL-"+fncGetResourceByResourceId("pub_number")+"-"}catch(a){}}function fncSetCookie(a,e){try{document.cookie=fncGetCookiePrefixName()+a+"="+encodeURIComponent(e)+";path=/;"}catch(d){}}
function fncGetCookie(a){try{for(var e=document.cookie.split("; "),d=e.length,f=0;f<d;f++){var b=e[f].split("=");if(fncGetCookiePrefixName()+a==b[0]&&b[1])return decodeURIComponent(b[1])}return""}catch(g){}}
function fncConvertSearchText(a,e){try{var d="",f=fncGetRegExpArray();a=a.replace(/&lt;/g,"<");a=a.replace(/&gt;/g,">");a=a.replace(/&amp;/g,"&");for(var b=a.length,g=0;g<b;g++){var h=a.substring(g,g+1),p="";if(h.match(/[\u005C]/)){var k=a.substring(g+1,g+2);h.match(/([$()\-^\\\|\[\]{},:+*.?])/)&&(p=fncGetRegExpString(h+k,f),g++)}else if(h.match(/[\uFF66-\uFF9F]/)){if(k=a.substring(g+1,g+2),k.match(/[\uFF9E-\uFF9F]/)){var r=h+k,p=fncGetRegExpString(r,f);p!=r&&(g+=k.length)}}else if(h.match(/[A-Za-z0-9]/))var m=
h.charCodeAt(0)+65248,v=String.fromCharCode(m),p="("+h+"|"+v+")";else if(h.match(/[\uFF21-\uFF3A\uFF41-\uFF5A\uFF10-\uFF19]/))var s=h.charCodeAt(0)-65248,r=String.fromCharCode(s),p="("+r+"|"+h+")";""==p&&(p=fncGetRegExpString(h,f));d+=p}e&&(d=d.replace(/&/g,"&amp;"),d=d.replace(/</g,"&lt;"),d=d.replace(/>/g,"&gt;"));return d}catch(u){}}
function fncGetRegExpString(a,e){for(var d=a,f=fncGetRegExpSeparator(),b=e.length,g=0;g<b;g++){for(var h=e[g],p=h.split(f),k=p.length,r=0;r<k;r++)if(p[r]==a){d=h.replace(f,"|");d="("+d+")";break}if(d!=a)break}return d}
function fncGetRegExpArray(){var a=fncGetRegExpSeparator();return["\uff71"+a+"\u30a2","\uff72"+a+"\u30a4","\uff73"+a+"\u30a6","\uff74"+a+"\u30a8","\uff75"+a+"\u30aa","\uff76"+a+"\u30ab","\uff77"+a+"\u30ad","\uff78"+a+"\u30af","\uff79"+a+"\u30b1","\uff7a"+a+"\u30b3","\uff7b"+a+"\u30b5","\uff7c"+a+"\u30b7","\uff7d"+a+"\u30b9","\uff7e"+a+"\u30bb","\uff7f"+a+"\u30bd","\uff80"+a+"\u30bf","\uff81"+a+"\u30c1","\uff82"+a+"\u30c4","\uff83"+a+"\u30c6","\uff84"+a+"\u30c8","\uff85"+a+"\u30ca","\uff86"+a+"\u30cb",
"\uff87"+a+"\u30cc","\uff88"+a+"\u30cd","\uff89"+a+"\u30ce","\uff8a"+a+"\u30cf","\uff8b"+a+"\u30d2","\uff8c"+a+"\u30d5","\uff8d"+a+"\u30d8","\uff8e"+a+"\u30db","\uff8f"+a+"\u30de","\uff90"+a+"\u30df","\uff91"+a+"\u30e0","\uff92"+a+"\u30e1","\uff93"+a+"\u30e2","\uff94"+a+"\u30e4","\uff95"+a+"\u30e6","\uff96"+a+"\u30e8","\uff97"+a+"\u30e9","\uff98"+a+"\u30ea","\uff99"+a+"\u30eb","\uff9a"+a+"\u30ec","\uff9b"+a+"\u30ed","\uff9c"+a+"\u30ef","\uff66"+a+"\u30f2","\uff9d"+a+"\u30f3","\uff67"+a+"\u30a1","\uff68"+
a+"\u30a3","\uff69"+a+"\u30a5","\uff6a"+a+"\u30a7","\uff6b"+a+"\u30a9","\uff6f"+a+"\u30c3","\uff6c"+a+"\u30e3","\uff6d"+a+"\u30e5","\uff6e"+a+"\u30e7","\uff73\uff9e"+a+"\u30f4","\uff76\uff9e"+a+"\u30ac","\uff77\uff9e"+a+"\u30ae","\uff78\uff9e"+a+"\u30b0","\uff79\uff9e"+a+"\u30b2","\uff7a\uff9e"+a+"\u30b4","\uff7b\uff9e"+a+"\u30b6","\uff7c\uff9e"+a+"\u30b8","\uff7d\uff9e"+a+"\u30ba","\uff7e\uff9e"+a+"\u30bc","\uff7f\uff9e"+a+"\u30be","\uff80\uff9e"+a+"\u30c0","\uff81\uff9e"+a+"\u30c2","\uff82\uff9e"+
a+"\u30c5","\uff83\uff9e"+a+"\u30c7","\uff84\uff9e"+a+"\u30c9","\uff8a\uff9e"+a+"\u30d0","\uff8b\uff9e"+a+"\u30d3","\uff8c\uff9e"+a+"\u30d6","\uff8d\uff9e"+a+"\u30d9","\uff8e\uff9e"+a+"\u30dc","\uff8a\uff9f"+a+"\u30d1","\uff8b\uff9f"+a+"\u30d4","\uff8c\uff9f"+a+"\u30d7","\uff8d\uff9f"+a+"\u30da","\uff8e\uff9f"+a+"\u30dd","!"+a+"\uff01",'"'+a+"\u201d","#"+a+"\uff03","\\$"+a+"\uff04","%"+a+"\uff05","&"+a+"\uff06","'"+a+"\u2019","\\("+a+"\uff08","\\)"+a+"\uff09","\\*"+a+"\uff0a","\\+"+a+"\uff0b","\\,"+
a+"\uff0c","\\-"+a+"\uff0d","\\."+a+"\uff0e","/"+a+"\uff0f","\\:"+a+"\uff1a",";"+a+"\uff1b","<"+a+"\uff1c","="+a+"\uff1d",">"+a+"\uff1e","\\?"+a+"\uff1f","@"+a+"\uff20","\\["+a+"\uff3b","\\\\"+a+"\uffe5","\\]"+a+"\uff3d","\\^"+a+"\uff3e","_"+a+"\uff3f","`"+a+"\u2018","\\{"+a+"\uff5b","\\|"+a+"\uff5c","\\}"+a+"\uff5d","~"+a+"\uff5e","\uff61"+a+"\u3002","\uff62"+a+"\u300c","\uff63"+a+"\u300d","\uff64"+a+"\u3001","\uff65"+a+"\u30fb","\uff70"+a+"\u30fc"]}
function fncGetRegExpSeparator(){return"###Separator###"}function fncResetSearchDisplay(){try{var a=fncGetConstantByName("search_help");a&&(search_help_node=fncGetTocNodeByLinkName(a))}catch(e){}}String.prototype.trim=function(){return this.replace(/(^\s+|\s+$)/g,"")};Array.indexOf||(Array.prototype.indexOf=function(a){for(var e=this.length,d=0;d<e;d++)if(this[d]===a)return d;return-1});
function fncGetSessionStorage(a){try{if(sessionStorage){var e=sessionStorage.getItem(a);null==e&&(e="");return e}return fncGetCookie(a)}catch(d){return fncGetCookie(a)}}function fncSetSessionStorage(a,e){try{sessionStorage?sessionStorage.setItem(a,e):fncSetCookie(a,e)}catch(d){fncSetCookie(a,e)}}
(function(){var a,e,d,f,b,g,h,p;window.device={};e=window.document.documentElement;p=window.navigator.userAgent.toLowerCase();device.ios=function(){return device.iphone()||device.ipod()||device.ipad()};device.iphone=function(){return d("iphone")};device.ipod=function(){return d("ipod")};device.ipad=function(){return d("ipad")};device.android=function(){return d("android")};device.androidPhone=function(){return device.android()&&d("mobile")};device.androidTablet=function(){return device.android()&&
!d("mobile")};device.blackberry=function(){return d("blackberry")||d("bb10")||d("rim")};device.blackberryPhone=function(){return device.blackberry()&&!d("tablet")};device.blackberryTablet=function(){return device.blackberry()&&d("tablet")};device.windows=function(){return d("windows")};device.windowsPhone=function(){return device.windows()&&d("phone")};device.windowsTablet=function(){return device.windows()&&d("donottouch")};device.fxos=function(){return d("(mobile; rv:")||d("(tablet; rv:")};device.fxosPhone=
function(){return device.fxos()&&d("mobile")};device.fxosTablet=function(){return device.fxos()&&d("tablet")};device.mobile=function(){return device.androidPhone()||device.iphone()||device.ipod()||device.windowsPhone()||device.blackberryPhone()||device.fxosPhone()};device.tablet=function(){return device.ipad()||device.androidTablet()||device.blackberryTablet()||device.windowsTablet()||device.fxosTablet()};device.portrait=function(){return 90!==Math.abs(window.orientation)};device.landscape=function(){return 90===
Math.abs(window.orientation)};d=function(a){return-1!==p.indexOf(a)};b=function(a){var b;return b=RegExp(a,"i"),e.className.match(b)};a=function(a){return b(a)?void 0:e.className+=" "+a};h=function(a){return b(a)?e.className=e.className.replace(a,""):void 0};device.ios()?device.ipad()?a("ios ipad tablet"):device.iphone()?a("ios iphone mobile"):device.ipod()&&a("ios ipod mobile"):device.android()?device.androidTablet()?a("android tablet"):a("android mobile"):device.blackberry()?device.blackberryTablet()?
a("blackberry tablet"):a("blackberry mobile"):device.windows()?device.windowsTablet()?a("windows tablet"):device.windowsPhone()?a("windows mobile"):a("desktop"):device.fxos()?device.fxosTablet()?a("fxos tablet"):a("fxos mobile"):a("desktop");f=function(){return device.landscape()?(h("portrait"),a("landscape")):(h("landscape"),a("portrait"))};g="onorientationchange"in window?"orientationchange":"resize";window.addEventListener?window.addEventListener(g,f,!1):window.attachEvent?window.attachEvent(g,
f):window[g]=f;f()}).call(this);
