function fncToggle(a){try{var c=999,b="";"toc-sign-1"==a.childNodes[0].className?(a.childNodes[0].className="toc-sign-2",b="none"):"toc-sign-2"==a.childNodes[0].className?(a.childNodes[0].className="toc-sign-1",b="block"):"chapter-sign-1"==a.childNodes[0].className?(a.childNodes[0].className="chapter-sign-2",b="none"):"chapter-sign-2"==a.childNodes[0].className&&(a.childNodes[0].className="chapter-sign-1",b="block");var d=a.parentNode,f=parseInt(d.className.split(" ")[0].split("_")[1]),e=document.getElementById("id_toc").getElementsByTagName("li"),
h=e.length;for(a=0;a<h;a++)if(e[a]===d)c=f+1;else{var g=e[a].className.split(" ")[0].split("_")[1];if("none"==b)if(g>=c)e[a].style.display=b,"a"==e[a].childNodes[0].nodeName.toLowerCase()&&(e[a].childNodes[0].childNodes[0].className="toc-sign-2");else{if(999!=c)break}else if(g==c)e[a].style.display=b;else if(999!=c&&c>g)break}fncIsSvgEnabled()||fncLoadPng();device.android()&&$("iframe",parent.document).height($(document).height())}catch(k){}}
function fncOpenCloseAllToc(a){try{for(var c=document.getElementById("id_toc").getElementsByTagName("img"),b=c.length,d=0;d<b;d++)(c[d].className=="toc-sign-"+a||c[d].className=="chapter-sign-"+a)&&fncToggle(c[d].parentNode);fncIsSvgEnabled()||fncLoadPng()}catch(f){}}function fncIsSvgEnabled(){return!(!document.createElementNS||!document.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect)}
function fncLoadPng(){var a=window.parent.frame_path;$("img.chapter-sign-0").css("background-image","url("+a+"images/toc-sign-0.png)");$("img.chapter-sign-1").css("background-image","url("+a+"images/chapter-sign-1-24.png)");$("img.chapter-sign-2").css("background-image","url("+a+"images/chapter-sign-2-24.png)");$("img.toc-sign-0-active").css("background-image","url("+a+"images/toc-sign-0-active.png)");$("img.toc-sign-0").css("background-image","url("+a+"images/toc-sign-0.png)");$("img.toc-sign-1").css("background-image",
"url("+a+"images/toc-sign-1.png)");$("img.toc-sign-2").css("background-image","url("+a+"images/toc-sign-2.png)")}
(function(){var a,c,b,d,f,e,h,g;window.device={};c=window.document.documentElement;g=window.navigator.userAgent.toLowerCase();device.ios=function(){return device.iphone()||device.ipod()||device.ipad()};device.iphone=function(){return b("iphone")};device.ipod=function(){return b("ipod")};device.ipad=function(){return b("ipad")};device.android=function(){return b("android")};device.androidPhone=function(){return device.android()&&b("mobile")};device.androidTablet=function(){return device.android()&&
!b("mobile")};device.blackberry=function(){return b("blackberry")||b("bb10")||b("rim")};device.blackberryPhone=function(){return device.blackberry()&&!b("tablet")};device.blackberryTablet=function(){return device.blackberry()&&b("tablet")};device.windows=function(){return b("windows")};device.windowsPhone=function(){return device.windows()&&b("phone")};device.windowsTablet=function(){return device.windows()&&b("touch")};device.fxos=function(){return b("(mobile; rv:")||b("(tablet; rv:")};device.fxosPhone=
function(){return device.fxos()&&b("mobile")};device.fxosTablet=function(){return device.fxos()&&b("tablet")};device.mobile=function(){return device.androidPhone()||device.iphone()||device.ipod()||device.windowsPhone()||device.blackberryPhone()||device.fxosPhone()};device.tablet=function(){return device.ipad()||device.androidTablet()||device.blackberryTablet()||device.windowsTablet()||device.fxosTablet()};device.portrait=function(){return 90!==Math.abs(window.orientation)};device.landscape=function(){return 90===
Math.abs(window.orientation)};b=function(a){return-1!==g.indexOf(a)};f=function(a){var b;return b=RegExp(a,"i"),c.className.match(b)};a=function(a){return f(a)?void 0:c.className+=" "+a};h=function(a){return f(a)?c.className=c.className.replace(a,""):void 0};device.ios()?device.ipad()?a("ios ipad tablet"):device.iphone()?a("ios iphone mobile"):device.ipod()&&a("ios ipod mobile"):device.android()?device.androidTablet()?a("android tablet"):a("android mobile"):device.blackberry()?device.blackberryTablet()?
a("blackberry tablet"):a("blackberry mobile"):device.windows()?device.windowsTablet()?a("windows tablet"):device.windowsPhone()?a("windows mobile"):a("desktop"):device.fxos()?device.fxosTablet()?a("fxos tablet"):a("fxos mobile"):a("desktop");d=function(){return device.landscape()?(h("portrait"),a("landscape")):(h("landscape"),a("portrait"))};e="onorientationchange"in window?"orientationchange":"resize";window.addEventListener?window.addEventListener(e,d,!1):window.attachEvent?window.attachEvent(e,
d):window[e]=d;d()}).call(this);function is_android_ff(){return device.android()&&-1!=navigator.userAgent.indexOf("Firefox")?!0:!1}window.onload=function(){try{fncIsSvgEnabled()||fncLoadPng(),device.android()&&window.setTimeout(function(){$("iframe",parent.document).height($(document).height());document.getElementById("scroll_anchor").scrollIntoView(!1)},500)}catch(a){}};
